---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: main
  namespace: minio
spec:
  encryptedData:
    MINIO_ROOT_PASSWORD: AgAYwKEYGEVkUrToR5/+ItdVWouZqXv295q3mYPTUZZlNh03JeEt9mrR1OgJqDWG7FC2sqqAu9BqjKaJKwfjAFtZb2Xh2SmT1G2ER72LwqutH8LL55P+g0v4NcMunQWvakzQokgo/ou0QRgJqXQzib3lsxKIcJajO6CO4RndI1rryaQ/PR+fV7ZT/DKDejEeuJAWzvo7/GrzpFgW3Y+Iz6fdegyrwy7QyoknDMzvmTKv6ZmzKXLAOPPVSwqQB0YyvEGkMr7jXKb1R9ivKNCUVOwGfj0RDTRCEA+7xb5EkxQ/jmxxAJ864iO41CxWrrai+FZUk9zb8Z/Yn1JivLXNGLNKayhhGRA48m/4PqyVf3C1/1KiXySsLoFHqsKQr8cyisJeSNIK/IbSRxyezQJIOom4ZfV4GNKUJkQPvJWfbnmliGNwQdCw+ILR+Lef2DUo/+eUBWRxc8mP0Ngrk2Hw0jHZsSH7OJmwo8cq/TwNaclzVal3VxPa3lUf92mvpwGuVpe8XfT5UZOgp/btub3rQQLqbxcoJDKIciPnveqy/ugDxMdCiZO1IT8jPIpt+QoRNzmmWGaBGm2qCaGhXN+ayniah1iu6sXFRYaA2ZA6l6EhjSmFpAfIO9z4gaZ4qwYZ+oo74/tlB3ARGcUwMVtgqzHvMuujKi4dZ+SHXPNnJFs0PtUlkjYB+urDqqiQOnaYUx++hNgkQq0W8w==
  template:
    metadata:
      creationTimestamp: null
      name: main
      namespace: minio
