---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: main
  namespace: minio
spec:
  encryptedData:
    MINIO_ROOT_PASSWORD: AgBH58GZDggYZYZg4th5j5qA4aapzZH7T5tWMoAGYrnNeZvEAI+D+4Gya3Ebq2BDKx6jsF/Hr4vwPilC014dVWy4o1b0QPu/hdu43u/JsSSk56/cvNqbzkj766Y5zWdR+6TH51cROq59Q1WD7yOxvMNKkEZ7WY8568Sve8q2sp0esQOJnt8swQS/DGz5lLAMnlacQLTIi5JlpRuPsrx2JL2tnYjfkug/6AGk3Monuppw+iz5BXTz7VbwrWziwS9VHXgjLq9ORKPaaUJNR8e1/Ecn4yW5AggcZEyuF9CMVYkSECIXYACpQUhKPeACt1oYmWQdOAJJhWvSx4UW90pnoDtugNuM+WXY+0oZWwDdWx6VfaLQnL/sQICJKpWmdpAiEqAXK6IXh4jDMCE1UatXxlvrgJIhqowQFpUwxNLpvkiim1yqP+LRIHQCHsJY5p0ziF2lJ2Y0jKxPYthKWZXx7LA7jEMMxNOUKTtmCKQLp3wHjHvcpMJ1Zj20KaN2X2BGN+FR9KCia5wloXSkEg59GAjX+s4xkL78SQjSAGsYxS14woxiJkmKQnoy97YkD3jqgsKr+V5t1rxeyNWg7wh4IH+4Db5XdNYoDik2tnY0GEq75QGRgu2oAM0LasYihssAgfr6PtQpMo42bjK75u0HlOj3cMQr3jF3bD08cRH+gHAaWvmxFS90+C4dMH0l+ZTTV862voZ5NoYMdA==
  template:
    metadata:
      creationTimestamp: null
      name: main
      namespace: minio
