---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: main
  namespace: minio
spec:
  encryptedData:
    MINIO_ROOT_PASSWORD: AgAX0eGCPo7OxAJMxTb85YXiwBB25FhJs0rIj5rHexGvZlGLnxqKeyTcopN+9Ad83AkVpaECRaZexKU91q4tp6lXj89HtIJwkHF2iEgbzEfLAFHlj4R469XayGKotYyQEsphribM+mzX4gpW5A5cZ6FT/O2XE286vC3YNDkpy0wFqkaNe+44Gl6HeanocN0EnBTxJiDw9oHF4smvDvSdQd6pVcCFTJSxWVUOdKkfnI8re3TXLp6ofJ7R+VUK8PGXevWgC0k7Fd+fujZGN638uqSBmyVLjwvneT2f+wax/HkSMjYsCi+LZf1HXy57MDsefRzm6aqVHgsZXFzVnH0ddjh9zoohO3jB3mkhqWjUHS2/lapk8oR2JfMQ2Z/Az19+rdtkCPWn/JP2ylrWElTyfsTLLEvHYL3NHANjpY+0yjXpMo0UwADMcfMtQoJdghvhAprHXP6IHrrPRSejVmh9f0Ssv7xfCK+UG/O5eA7xKBWv8xIcO3SBNqtNJOQeGKjdvOK8FKK3wbBw6pR9TenbakhNdIYZK5bgINNj3EbXqOxw2Df/Pesfmws6Oy/v07LvhUWE5+eOreyJUF5uySlUMSP3wYpAxn0LRtnsljHCKtOp+YxhA8MLRdp2uAna4UMvpGi4CFPq40ese8FeljTDoFTiTE2T55S5M20pHqTUgja0c5KkXlr0E9O5BHxFccafOlM4oWbxhuUoyQ==
  template:
    metadata:
      creationTimestamp: null
      name: main
      namespace: minio
