---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: main
  namespace: minio
spec:
  encryptedData:
    MINIO_ROOT_PASSWORD: AgCttKIGefYOAAznjeHpyMluSwFlzUjEQY9Mx5py7LrjvWECD4CdigN4/ukvCFdc3qPH+Q4Ske6gyRTHFCDU5k3ic0xwCWkgZHLq/h0hVzUo1PUQ79aDlWtWSAcvLlBhjyfGb5UKwhklXQHcMvT4JoQE71+2LnSmD1ebb/YKRl9Vusvcr6i0l7sn7etbvoXRcLqA4G7+RH/zpfoNW4QLiVXlkAKJYaAL5IeHK89gpxVPbJLtPIe9D59aNv9PvGZbjfwxtjGPmp4VqLh01zFghBzvSNc1+0fzZUHMDoAXEgUyMspY/HI0GwBR7SH7X7jAUpoWNs1HtNC5hD/+3JMhy0658LKHk8/W5ZfUtQPLTnwgoKTYzv1zAIpBBkSpBHZ6uF9z8o2xFFcyLohYgzdJrQtKK7eSJgh0buIWVmGjkpPT0eJ068E43ywnzkdQaHA/CbAHD3CZ111erlRm5FlZLlIeTmTZRyiWqgGGyFBsanM5h5PhoV/JxwoHO22h1gG3GQQRZx5epKGqNcT0Cdtr4nTGVr/6Gl9YL5P8thqoyiJpj2jORb2Sp2aaMifa0kYEkCbWIIP7iyZDZF79HgXk4rrgSutEC//YBW6/HJNSFRVxnfIJkBOwGkEvu+d3HVfHA6DZld0vXx+PxRAcWhkH5BL+ku0EF+ONmrziXjkLCmFDlFSTOfqDwBVB1JhOrFkSH21OeaM4ZK1/jg==
  template:
    metadata:
      creationTimestamp: null
      name: main
      namespace: minio
