---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: main 
  namespace: minio
spec:
  encryptedData:
    MINIO_ROOT_PASSWORD: AgAUBcAZ4FJCYehXCXDse1q9pkp8kjGaV0RkK3IZnmwxRPF8wbafMcDsabSN0X+4/H1zrmvdYNIjJlSkVTolhkKWi/JrR2wpr1P0fF/vXfETlXuLTfLHCKGSMquCZSvvDVgefZo8mZexiPI5f3gL7gzlxxFQK+sEAF08fxsp2Aft0kg9E45+TlO/35ZWPakihqVHylld62y5ZnojGis9RMyqbsOaQsXYlvIalzHNP2mJy++7/H0NZu+5t7TaDkVLNv/JfOGm6gX8x14HMxyPXB3coLd/IYIQ2PRCIE8Xg4vtm2fAiNAnD5o+FH/zJrfal2rcHAYQB0iiJmLo1lUzV/3FrbWOT1vZ10GQNa2d0HTTtdWGwANNquzkQavSTv9T6Irwh8hjACphf0E/xBvqrQtG4sEDCtU0FB2L5iVMZ5KZf4y5ojK85+YVu6M7Ax0y8dvdeQ8B3QNUN9beRgozZnkNvh66AjpdotjB0w44qjCMV73V0ELmW/p01kMJ2yc3cuNTQbwfC8nrHz6YYpCCmJdYSP2hOM5WsdY2IqYRaYwFpwqiFH09mgAWzYlvmLTAUBxB+IZHGUbzHzrlS0v4O9nIQjquIVF5YnRiukHCLuwQdicFPjd7FH6ZKdGIGCZKRE91FAoTMirCFokxE5Gs+RjpYYVfsiZ12dlV7e9V05TlgOdQSx55NScJpYsAHCnnAEZGl71x4/wAEw==
  template:
    metadata:
      creationTimestamp: null
      name: main 
      namespace: minio
