---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: main
  namespace: minio
spec:
  encryptedData:
    MINIO_ROOT_PASSWORD: AgApbIpdcGa+MLgl3yfaBfpDRCvg+M7juB6SrwmZHi+1DsGxErAakH6dXv81Un+hIwwmC931Fvs5xfAaDv1Gzyq+1AmLmM3Dy30Fi+iM9Vvicmw+i2zf4EeLTDr9rZCn4i+kL3hsr8AISYmIQ+GQrdbX4ghLzIqJLwaqO2KMjEv8n+qG3QSBhnu37wRwRpePhD3nGsPDkwJnkKcUNVS1qzmMa3nY5WH1V/7QOU/gTzG1lLlgkdexGGfb9EskwmdP0AXMWHc7mnUR9R6SYG28aLEcvVL2y7RGkUQwNf3O6AFxb00xCfjJrMH4lCxY1+D7z46U1z/Kv9DqGdgWJH6338UzU8xgm48GKyH4LITvehTUL2+BwRmt3o+XoY7Qt+sI+nC8av3VkKquL4lqg7q2JMFvcxaTEF/FibSbQ2jqxMPrFot1C9alwJqGzbOLCTpjov3tzAn5KTVfz5MD+kV4ixWeoZjA+8yIEfoMvgitTXuEcdPu4vM+RkmRj606Ih0zEtFd83xwTyIIZycJ+blFgJGM42oyXwDvU3zHuySkY7Jufuuoq6PG6oC3cmekU9Of0lLH9H78qDx81hk8udhXs512Kene4P3Qwus7vqGPuD4Yid0BszI1+Sgm9im01BAk9ePk5/+CSDQkI6FhyK1VKGatFO8W3NXYtNjKYSmmpCtKKcHh6g4Z1topGiM/EfJLgy4e2n9/k4wMRA==
  template:
    metadata:
      creationTimestamp: null
      name: main
      namespace: minio
