---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: main
  namespace: minio
spec:
  encryptedData:
    MINIO_ROOT_PASSWORD: AgBAAiM9OZzqvCb5Dp6n0Tma5MWKJ19iAVCePrWdgTeV3e1zAZSvz7VGqE+b/+KCB8ne1up/M5b9G06v5rQs6RUBXRt+f7l4idR4zVwgo/UCngmv782qd30WNheNV7WGmcMeO+d0RhVkUUnzlsFJtrLnrQZx+xNDG1EUx0UydNMQNpEYrDSo9HaSSmptc9fHrPcqJ37eM6SBLl7i8ygmqg4S1N910ESgLT/a/idGX6i65bhakXDg9XWI1tQ8yu0JyXFn3TS6HTcfDYDfgyvxmx4Qth+eBSckTnMQnwDgb+zi89rf5bbABV8EpKqcyouSpR4Ut+3nfPFreeobpy1AarbRSS4M1bN+P/s+YVPsA/lcs3aG02JaPKuKf9mWNWso7UXBjaq9LETqUE96B+ZKbnDO34cF8Oa6a9pdz33Oj0sCWLF+UkNu3td1op6Q1B/KayldsAGfhTGLYg4i4LHN3HGaGgRJTQx4ejWmARckehVLh0aFtlUMiii1o7XG4m9xR7J4EXMiP4KfEy19G+Kc0IiNLda+ilLms7UYoxxXugEuBU34wmyFsIaQZVLizmQuDX6GK+JBsqKYa5gVfuGGE+jtuekSBsj2UoDoQ1ByvCIO2img2xkE0gr3lNVB59iKRNdc3NGZMkGac5RvqrhxtAci80dKGv/8KxGvRB6Ve99JOvgHsmGN4EGT+9Ba9CqJWyC04b0rSzWXbA==
  template:
    metadata:
      creationTimestamp: null
      name: main
      namespace: minio
