apiVersion: v1
kind: Secret
metadata:
  name: main 
  # you have to declare namespace here for Sealed Secrets to work in proper namespace
  namespace: minio 
data:
  # echo -n "secret" | base64
  # length at least 8 characters
  MINIO_ROOT_PASSWORD: MTIzNDU2Nzg= # 12345678
