apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../base 
# Base
# - apps/dashboard.yml
# - apps/sealed-secrets.yml
# - apps/monitoring.yml
# - apps/logs.yml
# - apps/postgres.yml
# PG Back Web
# - apps/redis.yml
# - apps/mongodb.yml
# - apps/gitea.yml
# - apps/minio.yml

