apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd
resources:
  - ../base 
  # Base
  - apps/core/sealed-secrets.yml
  # - apps/dashboard.yml
  # - apps/monitoring.yml
  # - apps/logs.yml
  # PG Back Web
  - apps/dev/postgres.yml
  - apps/dev/minio.yml
  # - apps/redis.yml
  # - apps/mongodb.yml
  # - apps/gitea.yml
