apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd
resources:
  - ../base 
  # Base
  - apps/core/sealed-secrets.yml
  # - apps/core/dashboard.yml
  # PG Back Web
  - apps/dev/redis.yml
  - apps/dev/postgres.yml
  - apps/dev/minio.yml
  # Infobiz
  - apps/infobiz/infobiz.yml
