apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sealed-secrets
  namespace: argocd 
spec:
  project: default
  source:
    # https://artifacthub.io/packages/helm/bitnami-labs/sealed-secrets
    chart: sealed-secrets
    # this is the chart version, not the app version
    targetRevision: 2.17.1
    repoURL: https://bitnami-labs.github.io/sealed-secrets
  destination:
    server: "https://kubernetes.default.svc"
    namespace: kube-system
    # namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
