apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: infobiz
resources:
  - ../base
  - sealed-secrets.yml
  - ingress.yml
  - jobs/create-admin-user.yml

patches:
  - path: service-patches/flower.yml

images:
  - { name: front, newTag: dev, newName: repo.edtechworld.pl/edtechworld/infobiz-front }
  - { name: back , newTag: dev, newName: repo.edtechworld.pl/edtechworld/infobiz-back  }


configMapGenerator:

  - name: back
    # anyway secrets are hadled by sealed-secrets and we have to restart pods to apply new config
    # so in this case it is not make sense to use suffix hash for configmap
    # keep it simple
    options:
      disableNameSuffixHash: true
    literals:
      - DEBUG=True
      # - DEBUG_TOOLBAR=True
      - SCHEMA=https
      - DOMAIN=dev1.edtechworld.pl
      - ALLOWED_HOSTS=dev1.edtechworld.pl,api.dev1.edtechworld.pl
      - CSRF_TRUSTED_ORIGINS=https://dev1.edtechworld.pl,https://api.dev1.edtechworld.pl
      - LOGIN_REDIRECT_URL=https://dev1.edtechworld.pl

      - ADMINS=Andrey=omelyanukandrey@gmail.com
      - MANAGERS=omelyanukandrey@gmail.com

      - DB_HOST=master.postgres.svc.cluster.local
      - DB_PORT=5432
      - DB_NAME=infobiz
      - DB_USER=infobiz

      - S3_ENDPOINT_URL=main.minio.svc.cluster.local:9000
      - S3_EXTERNAL_ENDPOINT_URL=s3.edtechworld.pl
      - S3_EXTERNAL_ENDPOINT_USE_HTTPS=True
      - S3_PRIVATE_BUCKETS=infobiz-dev
      - S3_PUBLIC_BUCKETS=infobiz-dev-public

      - PUB_SUB_API_ENDPOINT=http://pub-sub.infobiz.svc.cluster.local:31004
      - CELERY_BROKER_URL=redis://main.redis.svc.cluster.local:6379/0

  - name: front 
    options:
      disableNameSuffixHash: true
    literals:
      - API_ENDPOINT=https://api.dev1.edtechworld.pl/

  - name: pub-sub
    options:
      disableNameSuffixHash: true
    literals:
      - CENTRIFUGO_LOG_LEVEL=debug
      - CENTRIFUGO_ALLOWED_ORIGINS="['*']"

  - name: pub-sub-config-file
    options:
      disableNameSuffixHash: true
    files:
      - config.json=pub-sub-config.json