apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd
resources:
  - namespace.yml
  - ../base 
  # Base
  - apps/core/sealed-secrets.yml
  # - apps/core/cert-manager.yml
  # - apps/dashboard.yml
  # - apps/monitoring.yml
  # - apps/logs.yml
  # - apps/postgres.yml
  # # PG Back Web
  # - apps/redis.yml
  # - apps/mongodb.yml
  # - apps/gitea.yml
  # - apps/minio.yml

patches:
  - { path: node-selector-patch.yml, target: { kind: Deployment }}
  - { path: node-selector-patch.yml, target: { kind: StatefulSet }}
