apiVersion: v1
kind: ConfigMap
metadata:
  name: pub-sub-config-file
data:
  config.json: |
    {
      "namespaces": [
        {
          "name": "admin",
          "history_size": 10,
          "history_ttl": "60s",
          "force_recovery": true
        },
        {
          "name": "user",
          "history_size": 10,
          "history_ttl": "60s",
          "force_recovery": true
        }
      ]
    }
