apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infobiz 
  namespace: argocd 
spec:
  project: default
  source:
    path: apps/infobiz/local
    repoURL: 'https://github.com/Andrey-Omelyanuk/dev-cluster'
    targetRevision: dev
  destination:
    namespace: infobiz 
    server: 'https://kubernetes.default.svc'
