apiVersion: apps/v1
kind: Deployment
metadata:
  name: main 
spec:
  replicas: 1
  selector:
    matchLabels: { app: gitea }
  template:
    metadata: 
      labels: { app: gitea }
    spec:
      nodeSelector: { node: main }
      restartPolicy: Always
      volumes:
        - { name: data, persistentVolumeClaim: { claimName: main }}
        - { name: tmp,  persistentVolumeClaim: { claimName: tmp }}
      containers:
        - name: gitea
          image: gitea/gitea:1.23.3
          ports:
            - { name: ssh , containerPort: 2222 }
            - { name: http, containerPort: 3000 }
          volumeMounts:
            - { name: tmp , mountPath: /tmp }
            - { name: data, mountPath: /data }
          envFrom:
            - configMapRef: { name: main }
            - secretRef   : { name: main }
          livenessProbe:
              httpGet: { port: http, path: /api/healthz }
              initialDelaySeconds: 200
              timeoutSeconds: 5
              periodSeconds: 10
              successThreshold: 1
              failureThreshold: 10
