apiVersion: v1
kind: Service
metadata:
  name: main 
spec:
  type: ClusterIP 
  selector: { app: gitea }
  ports:
  - { name: http, port: 3000, targetPort: http }
  - { name: ssh,  port: 2222, targetPort: ssh }
