apiVersion: v1
kind: PersistentVolume
metadata: 
  name: main 
  labels: { app: minio }
spec:
  storageClassName: manual
  accessModes: [ReadWriteOnce]
  capacity: 
    storage: 40Gi
  hostPath: 
    path: /home/andrey/k8s/minio
