---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: main
  namespace: minio
spec:
  encryptedData:
    MINIO_ROOT_PASSWORD: AgDSipS7z3JQHxvSN60nozK9cBaBkXJI8IdonjHGpsFJPYfDKqpuUk4YTTUNdXI3n6c8GoNjZMicoODm+egfpuLgAAx0oTVX2b8v6GkkvzxtqLwH4PvPNRh19jyISG6psH5iOlrYgiFwLqmvpimeroKcL0Oft9ay2EThJrI1bOJQjhJYIz3ghF+nU2GxS2BlphlfdLjbfPpA3eg6/3n6vNMTXmy5tw5sy/hYXzYwQP5hsJ+r+QSdnqqsolEcxzVl0znUEpitY6IqBgcoGQ+HOK5azxCe0V2JSbQMMvyElaoRdcDbFpaazdmcaGRwufCk9gCXE6GeJF7ZkZei58dX+cx6kT0nbf/2Z/ulkk00MeRf1/c1Qo7c4YCrbwx1ACc8rZq56DcuLReSpgEBgAOY1k7jQ3jsi00+VOgrX5DMrn6LJuNO8NZgCMoY45WurfpBksKTZQ5bNCmv6y05H3UhJMgJzLyFLuCi70jjVJ96JL5DDvUaw2lM8klZoqbv/GHJUEajVe/f7oBlm3bWr3JZ6IA9ri9tgugbLcmy5RKJGYF//swfvf23RVmZ03cjcaMdyHeeK6gfM5lpgo+ux+Qut4BkbP3hNThUdRIVcJA9/WaHJSr/rjd8inmSqMWlXd4MenjW4u4skoGhPHkZUXXLrSV4ZdLaIh57DE93kyez/nN8wTE0b2V6FJ5S9RG2hPSYEYY9+Sti5OqQyXkcRk+cHjHH
  template:
    metadata:
      creationTimestamp: null
      name: main
      namespace: minio
