---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: main
  namespace: minio
spec:
  encryptedData:
    MINIO_ROOT_PASSWORD: AgCcJVzJMxcOEm+lmS0wJvuFIxliOpYl0xw1tx7cEsk8PceKeSlz/XrWtGUfErVeFQDP53Fk8RWEiMO+XydPEUKtqL5eTEh/VhTWTi0Bo+C31qtjF20WLuW/hSPI64XpzOfV/oheJ0Nq2tsMQDkA+bXD9Fog5dwh2wITBZOBkHN8NKSEjauzj1C11+8aCZchcTAcMDRE051tVx/WCeQl3ikYcTYwbRy98jLWKh/6Osr1JptYVYXWgaGKX61EbmsDTOJoQ3A1SAYbkimf2KzRkmBq80H2C20/1T+edZv6m0GEJepRAzaYCRNElceR7nxHJOv+H86aNeoF0eh+q+8zNL/PLc+asy0wqNgYsPLoBOkhiYirlERffPr+svmvwCdUlonm/OTyBXbUvk/dHSIVJA1fx35ED4lADSGEfV4Rh03nZe4kbXdOYOHeP6FTkl1X8WZkGtn36Nije+y47ZMNiEwjlxxDflzSMAGB0keCgPLpzbsk59pXZ6FPY1vaW7XZo55e0Xm4VLWa/7wI5wQ4VUX0vIYdRFLHKbuHIPqXBKMFHvuPR7uY7l+ZEZTAF6ZEpvppt58JG6STBdKTUNp6jzMfBMjqU35Xo7I/kRwzjdkFVYV6XZbyM7alBKrSkYR16r+tadmd7tSsZEOqh23wYNZfsvMzLffwhUWa+uexNb/QYdF5kGWmKE1vr25Mz7einEcq85iBBjB2xijlVko8jcMG
  template:
    metadata:
      creationTimestamp: null
      name: main
      namespace: minio
