namespace: gitea
resources:
  - namespace.yml
  - ../base 
  - configs.yml
  - sealed-secrets.yml
  - service.yml
  - pvc.yml
  - pvc-tmp.yml

patches:
  - { target: { kind: Deployment, name: gitea }, path: deployment-patch.yml }
