apiVersion: apps/v1
kind: any 
metadata:
  name: any 
spec:
  template:
    spec:
      nodeSelector:
        node: main
  # jobTemplate:
  #   spec:
  #     template:
  #       spec:
  #         nodeSelector: 
  #           node: main
