---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: main
  namespace: gitea
spec:
  encryptedData:
    GITEA__database__PASSWD: AgBGI0wN33JtpQQto1dYZSglVHYqECadYZDxWr8+WGCjj/mN/DqDSc4hFriVzowJOhBMtxrhVSCdoY2bKqYQRkeZgsK7QSp8hY/Gl2TGEgGKlgGLVuqTjTJuuETLLz6AdURpgJCN+A1+tNuRqSAo74eO9HpqDmZnfIsvTP2ySBY0q+KdK6fvxZs2iYL0WDQinCnNuaYC8hxVBSmK1dpog4aMNOAronseK4DXmPKwNQqkqTUWyXuL4HW62+wk0URTMvD7ckjNzANQo5kad2CSnmTLRbU8R+2ximC+xjvrzmBkzmEVPUHGQqwnslKo/irAKfwELlc8kM0kcUUehxd6rIFdg9iKPpaG4s3VhGc89qp8CmJjtIlDJ84cToj8pVY8ES+J8g6l++oYpAHkoRvkHhsx5JI1XxpPeCkzrLW+FrqWIFs7eI9BqGUw4vxxCnYh8ycNHb2hdkLiBNWuXLhfhsF0NofpJzqHmcQDN4fPq4N25QM9j9iXRkXBi3cPkpt5ni8+1rrx2ZyFEvtaQU9nUPVpWHRPZ72xHET636HXCNTt62NE6j9EXWdQ9Im8nqp3G3a6uiKWlxz0yH77umcoFtUpP7Q0CTfBYADDFLmeUQlb42WoMnQ3GAv/kBGsyMaiyUICZ0oZnelzLYFxrC+XAvzyj9VgsL63N4B/sMPIELH4LF9t6Q+A21bm3ebgsanrboWoaBJl0H8=
  template:
    metadata:
      creationTimestamp: null
      name: main
      namespace: gitea
