---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gitea
  namespace: gitea
spec:
  encryptedData:
    TEST: AgB+9Nixb53GUIvniWB7wV9u+7Og8yFSBi4hpkEOabwFwFqF3C78LOOwgeuBzYNnyIyYhsZtGwjqpVe40Z+Hzl5upLjZ4mBDl0w0BXzTGMizjYbx7n/F3xiFLtRTDIo6WB8/xix6bxCmCjeE7Os9nGUXpIO+XezaxlKrLbxEN7645jp4cCEmr0sQgVXIXltx+g/l2OLRBkPYSo2Y+2Hl4d2e33F5urbdyWhMCSKIEVJ1yA65V3dgKYm2JqEOYYv2nyPHfJ7CurWdGmbq5xNRzJA9D4DMwNyEr6VfsiKoq9z7lSfAwcEBKsg9gp91WbDsU6ICISzZiaJWnmISITSMy7vzNdbNNN6DN+ZfUX3LnqoAXMCNeGcEfJ/zKsbkGfa5mxTWhhc4m6RVHnotHYBA9cab7MrmjbmgRwhEeLeLWencC6OKkOOk4QbVk3kYRuz8CbZ05+OfA3C1/FMCrSiOl0iHRLw2Lz2F4LbILzi7Z4ww26wEnb3/k8GIGZR0qUGm4HxD47fGNeMD6WTi0RNmkMj4E9OK8hHO+F6EEuxseash7y9RyFswCjshDouxaYmVezs26bIcZewdn3A5rsr8iFp9qYOkrn9ra3FucTQRSL0WCTXmHSYOsnlEaBuFBTHURTk+iSVVqcZDuYNFnEMeOT298k6g+KBEnjYvg98w6Gj2LNfsb4cl2stqrsoZ1tAWyGb01zyAfIA=
  template:
    metadata:
      creationTimestamp: null
      name: gitea
      namespace: gitea
