---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gitea
  namespace: gitea
spec:
  encryptedData:
    GITEA__database__PASSWD: AgA1i1oxeZXII0r8GtauFlT3nZWwUk3MdJvZNPNkMvzPZr+aZbdlJpwcOVs41ixHcjbIkGwQTmlLGhJDZNvuSui5dFQJXVWWjX0ru/bHrwPO+6t1kqs+H4yAQYXdDyrZbehovqDg0tnK9PhJfWnqHPvSJRP7IERtSBFEMwSaiMWI4He0tss/36Y/foxObZcFJRVczGQzfpHPCJDcL89uVPeTtR5ZibkL5Eju2QNhgfYmS6PzYHF0499X5FugZCwRE5Z31+hTuZkDrN/VLxJGGDcWvYZnWzgYEsI63wit7XsywoU/KO0/tGyXzjGzMNBP3STUJ4G255eatyLLb+2XlbKY1GtFEoUKME4gcNexXVqEkOwoNJd+2hg2eBuPGT31XVuT7GG6ouUgWScyYUwR3Rhusbceas/X6v9XZp0Mgmovr6j6RdVDrtulSU7hOa8BF0CKVM6NDpj/9Oz5zxeD4F3MhbbQ6lw/slmFUz4Opg1PTzp7YcBjdpof0ID6aR4R/A3OwJTjD2M4pnktWRzq9DJa5VKU5b1TvtbGoj4c6Fqw0ZZv38r9y9HWTRWRW6GclBfiDV1oBigc+xN4uC4kxnXjSxjOI9yoqLYJiev2TkjmO8FONGS/Tvts+dFy7pg2ls/0q3837CZ+7cbBQKj87Sms5ib40WxGexgH7eOinf6CfcGjaMVzfM3/A/KG0bFgRIdlfvmxsUw=
  template:
    metadata:
      creationTimestamp: null
      name: gitea
      namespace: gitea
