---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: main
  namespace: gitea
spec:
  encryptedData:
    GITEA__database__PASSWD: AgCJkg0fbJiLOpBhbXRFomsF04HGiYkRq5ktR+zQWaPTsjrloyz3ZgJQZ+WOzKA5UWyYVk+xuZ4IRQ7/rDYUoP+mKs/CG7wwcXC6zEg4wMlD8K2jYrr23Kj/HbJZiEwF9cepti+WNfDoXmwIO7ZoBNJBUhp4vLyXg43uo6HOkDazS25dTfOXpKKu4KaUrZWv0K5ssgh0aOdR3/UOUu3LIlEUJBhTV607aNvk28AJ74Vd3khHK51eZsClkdYXBYhrwphITMLzQcb2lhoZVVhocvWHhzRn6BUDx38TUexLJvtFC8+lrURqaljzobG2N/lv5XplkgPh+V05KI2YLpu/505tyz/THV2WVnu/9TN8jkTU7ZuILL26LPlQfeaAMcwqDlRfj76ZmmINOLUFLa3BA16r7nB9XXPeFYiNfhTuq3d0gd2z3IdwhBoMtHHKbEVGymPM12yyUx5uRMTPo78Tc5K6QnqCRNungqNEa9V8Tu11+cUg1sbXgwuJxVB1GX1SMLo0w6RYkoydPGcavLrAp+Tg6GGoONyajvDpAKrKv4oxRMqz8j2gFwrrNTCUVrlZVjTKW4XrOtJIOSz9UAp9reVz5/rtXrigSTraakdr8pJYBxATOe6+SDyoxEhoTKKoEXcvmYJ+/WDnBEsbUgxALB/COQC6ZlaHKY1j+JiBk+SYiLeKOEypEE5x1fJ+M2tf/5VNEwbkUZQ=
  template:
    metadata:
      creationTimestamp: null
      name: main
      namespace: gitea
