---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: main
  namespace: gitea
spec:
  encryptedData:
    GITEA__database__PASSWD: AgAICV9uYfuPc20vqXAE4Cy1v7mBF2NUIKvD39LojNV5Uzi3jVh4c3ydXYmAvFui0qniqtCseUZviNCK7nBhyJoRp1yQl5G2QYoPZzKa41MFTBA5ocJgLIuU/GcBQbH7Muct1iZLG65xynRWiQxN3Oq989E8pp6WMl4yxLJzKV+78aCtWQO0ImEXmrafzrO66nia+Scv/qIWb8A696yztSXx2rYwXPZLsYak7nAQbejBFx8QOW2q+L3SR6czzeeiVIhmRqOk4FFzN6b7nbpv1B+M1RXqX8qS8YF+WcYZTxTqt0bRqPv11txSHpHoLFi4gXYCn85nW8jyLJQYln691NTteVi6ASfcLi7npjkWDdFZAmW4Rk/oShnoXEgkdgkpSm1/elskwRCe/NZ9tuezquFaOCR4J9i6D5NoQGL6PxP7ww0YSjj9a4l+/kEoS0lewFYhU+L9hyy9s8uYnRVR+QolVbDnoG4Y+MTut5D6IsMM/STGaVR4oq8WOuAwhp0zflWovDkDuqjCAd4rT/HZZiUlWCv2YQLCSBmrp7pf4w+jc7cL/IcRippwgJyZ3f5PBXv0y9FOnmQg0qeAoRAcGoEBJ1iNifAmtgGLnwdaQpRJplnspu8pxQJNoXV92TrUNkW6TVIG3eyDh7MhYbnmlWqNHZxiNN4sXaodwvmkPyVuzM0Wjnj3B6UZuGfqn9CYhv7bdAaNbQI=
  template:
    metadata:
      creationTimestamp: null
      name: main
      namespace: gitea
