---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: main
  namespace: gitea
spec:
  encryptedData:
    GITEA__database__PASSWD: AgArQbMuQOc0/bVTVqRXS9vsMV6nXm1R9DuivDa0bM+/L5rq5wXvt2qzizGR35cOMJKr6D+HtrYTdCo6kuhY/IRd2dorSbcYEacfUaCc4ghfxSiatm/ujbEyXB+YbP/sfFSUfqHwh178IZT7MXhGfrkXrow2LnyHkVBJiIE7ZrIJOZ+Bw80ys/p++rZbGWkqlJjGZi7hO3eLh8VnzJsYrFH2qMEX9/49g9huBkH54gbvHUf3sYTjtWIna8ZSorCb5c1kDKiXM9geTp0+GZ/fOpuxqk628gE0ccTpBVBvCR/N4xqsItCGsp4G98rmrZFNQn/3T6XuQ5OFu1WUBgZiHPIdZksYaD/NBBD0r4eHiE89vl/xwjF/bkRy8OhEc3flth7bfhoAGcFI5E/a6Kw0dRKJIiw68ghSAlt7lG+U8LOG9uNR4MlNDDRA4+hPSulL4mCjZe7k9OKFA42HHJIKjz6IybY1xRa/c+09udoJm9RGQuLvP7o6uQ6uQx+XWW1LyNVxs7SNixvk2e4rIatcp71BGUTwYg78QY0hdinwGkYzx8N7JnHEx5sJKBSIRyXpQhy/n/0me9/K79exHz7x5EXNSMqtu7SXpm9R11Ml5dbPyPLFxKCmKcnp/R9V4BY+hc1UbkZng3DuV4LoUTDi0dCmd1G5bODsFrti/UTRkSLqOsiMWXyRCnwUBn+O1+MibZeq2+MbY0A=
  template:
    metadata:
      creationTimestamp: null
      name: main
      namespace: gitea
