---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gitea
  namespace: gitea
spec:
  encryptedData:
    TEST: AgAJZHzCXf29/IkiZ96T+QsKYE2TS/qLMELisM9y2BEhoIlWtAuSSe1LAKJ6p3lnr7QW9WgGRzHZAsX3LCpXJDG3Gls6v1TGZBXKv6sSYeeyLtUOeDL1Y5uiiPgpXS0tz1o3Rs0pZee3X1ZBphr78Nfyd1aU4Ds9v7lzeQf8bFQum2+G8g7upBCrPBjK8+HxjiNbhC/Vk3P2vE84frcoPdCHPJxj75mnGO7QPgVNcl4ie5cFx1aOs6VaignClTsWou/iqicMHSARRVcdEU5aTLu8SyOj0iXxre4xMM25Nsw0FAkn/CrUQf9KcSjuQ0wwa6xbYp+qbcNfSQYT4ewcG6gdBC5p273X0DQYKaH7RpiNUgNGABT0S7k7k2D+4Da/mwDNRNePjZqJiKyEnUuKKkgfAV/LVk6OJ7A69FfvIKJ9AiXWrboKqY3f3uiYRtIGP0FDz1oKw7IFWiVdivpf94aME6+M9kRXwUjhjF6HzgWuts/EQOR/GRvKp0m5zIdPk5poXD2D5OSr21b/Z3NsMGd6S/hb/sZHasX1EFqFuI6YDhNlD2JtZT03b4vDO0wojpBtjA5yo2bhf1uWC5JuGCBZ/TFZhgyQenoAnft8B0a32rTCj006W0ADHimeIMvo6ObdQiq36CyeDmhoBfDn7Gfgq3cO1sSkEPQhEI7RlZ+ZkMHPgs7gBWHL1pRZm2TE/iMNdfa3q/A=
  template:
    metadata:
      creationTimestamp: null
      name: gitea
      namespace: gitea
