---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: main
  namespace: gitea
spec:
  encryptedData:
    GITEA__database__PASSWD: AgAYecxYlRK3czQS8FSUuvlFzKOC3e1oD5NeBhYymnnIVUjPxNGXU00Yz3JsviwcvfYVz9BcHSKkVGYrX4IznZEZgN7iMuLFy4EaBzzaZFzHKVTbTnEwrhxlMri4uEx+59i3L7vhn43R/lkAkrG8wxjNQlMMKMzR2MsSO+1cKBG0riU1zTCBE66tj4G/u3SivZwc6M5h63NfabWNnq9VCBZT7fBQgTm8oYDC+tq1ce+qezBZTuqynerXRtfE8Hj2rK0bn8+AJK3nvUMlXFT8iGhWQzJfHFX6jaar+C7XPP9+HwdSi2OjiuXuxQ9NZ676ezQAZQGUnKGV+xa2BGghb0onrNLCNLuqJaJSuHyZfIxOGVwx00Uy8oGnlBMlXEeFg7C/9QEMWze3hr4XcvgPJ0LEnOKmTI5Hw+uv5FF0UVLOXeNWKdtZDuIMZ9jRIAhVTxBox2Qmo+qy3PdSyU58bKWriWx+YxI9VB9VQpaeVAii5kWeOY5Tk7iNhTNGbMRr30GWIVcSGiGnfInBFs5Y+ihLGsX4D71G6Z5iIAFwSYrHewpfTBES3X9ay2xb99eU6kQ4bjVJn9Xm5x9DxU6BAkBemKVfm2LEjd+nuIHdWMMBCUGp4rEtX9fevMTVkwROBoPBydSyBLFnbT5EiNlZPZFN1EMbPp7S6HuC46wegRGS4hWhR10tVddk0pJp8Nc3hGNS1mYlMJQ=
  template:
    metadata:
      creationTimestamp: null
      name: main
      namespace: gitea
