apiVersion: v1
kind: Service
metadata:
  name: gitea-outside
spec:
  type: NodePort
  selector: { app: gitea }
  ports:
  - { name: http, port: 3000, targetPort: http }
  - { name: ssh,  port: 2222, targetPort: ssh }
  externalIPs:
    - 192.168.49.2
