apiVersion: v1
kind: Service
metadata:
  name: main 
spec:
  type: ClusterIP 
  selector: { app: infobiz }
  ports:
    - { name: front-http,   port: 31001, targetPort: front-http  }
    - { name: back-http,    port: 31002, targetPort: back-http   }
    - { name: flower-http,  port: 31003, targetPort: flower-http }
    - { name: websocket ,   port: 31004, targetPort: websocket   }
