apiVersion: v1
kind: Service
metadata:
  name: back 
spec:
  type: ClusterIP 
  selector: { app: infobiz, component: back }
  ports:
    - { name: back-http,    port: 31002, targetPort: back-http   }
