apiVersion: v1
kind: Service
metadata:
  name: back-flower 
spec:
  type: ClusterIP 
  selector: { app: infobiz, component: flower }
  ports:
    - { name: flower-http,  port: 31003, targetPort: flower-http }
