apiVersion: v1
kind: Service
metadata:
  name: front 
spec:
  type: ClusterIP 
  selector: { app: infobiz, component: front  }
  ports:
    - { name: front-http,   port: 31001, targetPort: front-http  }
