apiVersion: v1
kind: Service
metadata:
  name: pub-sub 
spec:
  type: ClusterIP 
  selector: { app: infobiz, component: pub-sub }
  ports:
    - { name: websocket , port: 31004, targetPort: websocket }
