apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: gitea
resources:
  - namespace.yml
  - ../base 
  - configs.yml
  - sealed-secrets.yml
  - pv.yml
  - pvc.yml
  - pv-tmp.yml
  - pvc-tmp.yml
  - cron-job.yml
  - ingress.yml

patches:
  - { path: node-selector-patch.yml, target: { kind: Deployment }}
