apiVersion: v1
kind: PersistentVolume
metadata:
  name: gitea-tmp 
  labels: { app: gitea }
spec:
  storageClassName: manual
  accessModes: 
    - ReadWriteOnce
  capacity: 
    storage: 20Gi
  hostPath: 
    path: /home/andrey/k8s/gitea-tmp
