apiVersion: v1
kind: PersistentVolume
metadata:
  name: gitea
  labels: { app: gitea }
spec:
  storageClassName: manual
  accessModes: 
    - ReadWriteOnce
  capacity: 
    storage: 30Gi
  hostPath: 
    path: /home/andrey/k8s/gitea
