apiVersion: v1
kind: PersistentVolumeClaim
metadata: 
  name: gitea
spec:
  selector: 
    matchLabels: { app: gitea }
  storageClassName: manual
  accessModes: 
    - ReadWriteOnce
  resources: 
    requests: 
      storage: 30Gi
