---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: main
  namespace: gitea
spec:
  encryptedData:
    GITEA__database__PASSWD: AgBXd10r7VtsvsrBu2AjdPSmfyECZQMOyQT3bR4sXpF68zTB2BXm0srZF8ZF4WxYIt85uJLgh2u2U0XN1zPWYUN1AFG/oCpOzDy6RTawu4wWzijcdzgGJYc0gQHWh6Ou7+3lVMX9C1EzCqhprm9jpmy0quc8FLb/iMcyss/UBkEvzR3WZM1lp0+y9HwSPdtGjL7rDfAq+6ku2/5UicxNDIoZiVfRwAze7Fvc+h70HzgWpG7xQMPoLehwEU12kFh46ADJutXtNo0tL94sZ/1T9536nJxT4bHaF6p3WlO42Zg4pYonI4MV2FseR3Ce5vB+DRDDiFPi6dvB+orz7OqOicyn6xdF4YPcekiCLzRiDsXPEJFF1rxlTHRhB6x8C7XqWOdV2AQD+9iIC2wFR5K9ae4NZEhd/gMakPL8fAG5RSaCIKFSpSaeVn0Oi1DPxU1GEgMZGXqzwrb+BSREVYZLpxQ4jBMeOiwlioR3WRZJA6IbHOqY3yyTXhDfp0rVQDFMSaI2KGPHuDI4/KjI0Yc/vmKN2ZW4RMqMn3BWSC8XXjRvq/4ddG0eCZ2jlisVcR3wPFCgcZ+xNvlv0YPJNExRv43CHwRe6ydor7c6AzoQDUYXhn3+prHr06trVQj4do/YJMFsbxMv3wJeQp6X0tLNL73bgPD+G6zuzucf/8q2VDDR18+Gaym+Sp2jdxZwHA3HI0V9ggI3fqFwddeGxPM=
  template:
    metadata:
      creationTimestamp: null
      name: main
      namespace: gitea
