---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gitea
  namespace: gitea
spec:
  encryptedData:
    GITEA__database__PASSWD: AgBQY+/zVmybEkIlnmTH+hHslC70FG+GdKwABOgkZF6E88vQ77crPAbyuNFd+o7x65X7V80rIt5nWR+9XfB6nqx4FNsRQ08iZp0szQiHiM2fFt3+m5VKdKUtlQMRb4TI9FrpYhPE1vJ61sn5vTUQAKeg5uzUQl0je7R6l1tof8rR4lZfVrba7xoneg63SH4Rt36wzqWOS7GDCvMdIBCAZnjuucrtaGlZ2shOjaJNl9m97IXoKL2OUn9jq05Okn6TWMGXvhRALFv2ca98T1b9LWzBWyERL21+/1HN0yYfLVk/V9M/bi03g1q0hRkBIdU4ol6Jw06Tc0+nHspPnBDGlxC2cjL5d9vUNwDX/Jrol5qFwYC7KDvbXglVJa+vBGERqiFMAIKYOB48X6j1p9R0vo3hxpqfdyGpc6DFZTgJjd80BNa7vdnkPp3S37s5qtQvKA03/4zvrVF90wEbbHfrk9dnuOJ//wc0TVdS1BHijAWsjKe/PPzz5AqaGT2DaGDXXmQgb0sip87lFJRyH/jbsodDjUd9OFzEbuRESOkdeS6BysLHAXlkuDCxQrLFbkb20LflvTd5p31jz7kHTqWKoY1UM9ElVg1uL3Ck1eL7BUv9XLVB1QCU/2AbclUxm4HmQoch6wFcYfFn2Kdk+UHivVBi59IBr+Fwzdx8Fn/mC4SW7FLmTsTC+bZAFrntS/WBhsAhMCmi260bwlgtNDo=
  template:
    metadata:
      creationTimestamp: null
      name: gitea
      namespace: gitea
