---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: main
  namespace: gitea
spec:
  encryptedData:
    GITEA__database__PASSWD: AgDbDuFCNH9o1063Vwfhn7ZQEbJ/pGUFAjzdH9/kGzvan0WvlYw9DxCPJM+4jJXzLExtMje3viivtcqqj4bkmnBc67fXBs6CGwRx9/UZGyQQbICp5JzKo/XfQgZGiojR04hUn/6KmeGA+XKqN9YiNhCrGiPnPoz3C55zAQJK8XPLP1och8W1SYEs9T3AHlbyD/Ee9IsizW5L7iY7mV0O+LnBZmtT2uOAdx/Vu7+bjdxpIAHIadDmaCdblEH7tosVco26HdP/yGUvpAPRxs/7R7lSuhgTx6lBqymUHZvmkxXG75MJWYa2lGRU4RZ77/USJ9Vfi/IK+Sklv1ScYsHcEQITgJXa2gvmLOryDUD66dCp0xDdHk0Ng0IpkN08o2mDCIMLd2/JfXJAO5COVUSPHgZITTrQw0gHb+LVMmUPD9Svw46TkszI4qpUBlGLmzdOb1IOIVj6f71VCkHb/qm67WTqWMI0nn5WPoVEoG/KYwIgWLObqPl3mepY7mxlqK/hGGtIPRYoQ9EDhXxUgHMwPuv7s2qUI7LvU6jk2ABffMPZ4BDd/d/bXtFeDeALu1044mItSNQkEkq1DMsBUPxxvkU82CnZazEdazE02WF3eSoIkUKfRhn+cXFsstRNrHYlN/v6ARYLbQCgv3pYFTzE6KONeudV5nQDpp+xKErMoULpmU089DR2bSTS3rKivkTpdoVXeGSr2gEgJ0DxcYQ=
  template:
    metadata:
      creationTimestamp: null
      name: main
      namespace: gitea
