apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-master-data
  labels: { app: postgres, role: master }
spec:
  # storageClassName: local-path
  storageClassName: manual
  accessModes: 
    - ReadWriteOnce
  capacity: 
    storage: 50Gi
  hostPath: 
    path: /home/andrey/k8s/postgres-master-data
