apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - production.yml 
  - staging.yml 

helmCharts:
  - name        : cert-manager
    releaseName : cert-manager
    namespace   : kube-system
    version     : v1.17.1
    repo        : https://charts.jetstack.io
    valuesFile: values.yml