apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-production
  # namespace: cert-manager
  namespace: default
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: omelyanukandrey@gmail.com 
    privateKeySecretRef:
      name: letsencrypt-production
    solvers:
      - http01:
          ingress:
            # ingressClassName: traefik
            class: traefik
