apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd
resources:
  - namespace.yml
  - argocd-non-ha-2.14.2.yml

patches:
  - { path: node-selector-patch.yml, target: { kind: Deployment }}
  - { path: node-selector-patch.yml, target: { kind: StatefulSet }}
  - { path: enable-helm-patch.yml  , target: { kind: ConfigMap, name: argocd-cm }}
