apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd
resources:
- namespace.yml
- argocd-non-ha-2.14.2.yml

patchesStrategicMerge:

patches:
  - target:
      kind: ConfigMap
      name: argocd-cm 
    path: argocd-cm-patch.yml
