apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: infobiz
resources:
  - ../base
  - sealed-secrets.yml

images:
  - { name: front, newTag: dev, newName: repo.edtechworld.pl/edtechworld/infobiz-front }
  - { name: back , newTag: dev, newName: repo.edtechworld.pl/edtechworld/infobiz-back  }

patches:
  - path: service-patches/back.yml
  - path: service-patches/flower.yml
  - path: service-patches/front.yml

configMapGenerator:

  - name: back
    literals:
      - DEBUG=True
      - DEBUG_TOOLBAR=True
      - SCHEMA=http
      - DOMAIN=dev.localhost
      - ALLOWED_HOSTS=192.168.49.2
      - CSRF_TRUSTED_ORIGINS=http://192.168.49.2
      - LOGIN_REDIRECT_URL=http://192.168.49.2:31002

      - ADMINS=Andrey=omelyanukandrey@gmail.com
      - MANAGERS=omelyanukandrey@gmail.com

      - DB_HOST=master.postgres.svc.cluster.local
      - DB_PORT=5432
      - DB_NAME=infobiz
      - DB_USER=infobiz

      - S3_ENDPOINT_URL=main.minio.svc.cluster.local:9000
      - S3_EXTERNAL_ENDPOINT_URL=192.168.49.2:9000
      - S3_EXTERNAL_ENDPOINT_USE_HTTPS=False
      - S3_PRIVATE_BUCKETS=infobiz-dev
      - S3_PUBLIC_BUCKETS=infobiz-dev-public

      - PUB_SUB_API_ENDPOINT=http://pub-sub.infobiz.svc.cluster.local:31004
      - CELERY_BROKER_URL=redis://main.redis.svc.cluster.local:6379/0

  - name: front 
    literals:
      - API_ENDPOINT=http://api.dev.localhost/

  - name: pub-sub
    literals:
      - CENTRIFUGO_LOG_LEVEL=debug
      - CENTRIFUGO_ALLOWED_ORIGINS="['*']"

  - name: pub-sub-config-file
    files:
      - config.json=pub-sub-config.json
