---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: act-runner
  namespace: gitea
spec:
  encryptedData:
    GITEA_RUNNER_REGISTRATION_TOKEN: AgDIT34PQEbIB8FELygRS0/QddA6pr6/rrdALqy5p8L6Z7jteCpsSzCbZXw9rVcB/3hj5dAlzDB3s6Uc9tN0rakD/kW5J0FFWCfyVDI0ZPYo02ydbq3HiwDRKK9dXuBinFtL0w00/yPkoJiVgHO/rk46Thbus509XGJ0hI2502+JsxVnWo4huqD8s+O2xdwJacVSN7fCCqBXvg2YUBUQJFhuKfGNZSI6vjtcyqAqNsFpnhvF1vw0hK49WHFfdTPMmI0EiHId5HWzNpYNVMkmsFcmLpz198RdWsV9SAadYD6KSHWSZ3/P/J9ADkmETnZC+ngkkLMr7rjYeS2Dp2/mu6WKylp78VV+CTCeilU7DKRIXaiN90VyzN0jEChJjQwYdRflkFBjsE/ylO8hhbeeKTCrxE0rVTxOyZ0iVQGXdDetFc1HDPqKkGINfrJMml+JAQ8XCxmbflpo2eHv3IEztRBy5SK/s83pfqO4uVQdV6gwVybpuz2ugs7GkxlNM7Iz2RAm857GMR68U+VrKv+Ea0Rgvg+IwFVVZpxScuB2YW5VaQWAMn5qmoptANyfhlTQduKK0N8AbcqihXAiIlKhJYczzSaMQtst3swZfxiXqRFNwNQOcreHMdV3DAme5aMKd/GTKg9tkCy2bQ+g6G0cafYX+CFwsuRdNBVtLWaRiTdgVLJB9Stb+rns5qn/8D21ZZrHlXtPsWvUNR0yiQJ7YKL6GtW7NCnYD5PFolmXUkYUMCM6CKHvm3gW
  template:
    metadata:
      creationTimestamp: null
      name: act-runner
      namespace: gitea
