apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: postgres 
resources:
  - namespace.yml
  - master/pvc.yml
  - master/stateful-set.yml
  - master/job-additional-dbs.yml
  - master/service.yml
  # - replica/service.yaml
  # - replica/stateful-set.yaml
