apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgres-secrets
spec:
  encryptedData:
    POSTGRES_USER: AgB+... # Encrypted value of "admin"
    POSTGRES_PASSWORD: AgB+... # Encrypted value of "password"
    POSTGRES_DB: AgB+... # Encrypted value of "mydatabase"
