apiVersion: v1
kind: PersistentVolumeClaim
metadata: 
  name: gitea-act-runner
spec:
  selector: 
    matchLabels: { app: gitea-act-runner }
  accessModes: 
    - ReadWriteOnce
  resources: 
    requests: 
      storage: 5Gi
