---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: act-runner
  namespace: gitea
spec:
  encryptedData:
    GITEA_RUNNER_REGISTRATION_TOKEN: AgAHgJaMLtgV6+cAwtY7cOz0Tb6m9zky0YtVFFf9Y4/5Uy/9/e16sMiSucQ2NAvmRWTS57x0+96NU40QzFV4HmN+AUPdZ7wIshkziIL22m0MBnkGfJSqs1Fn0o3crP5LdyKonZ7NcQaxj3N/w2HkPSDsjiXEHRxuqPMo61SXrk1zpgU8JZYDBbc+UZwl3DU7L1Uy4gYiB5E/ZQlMYf/FYRl2Zr6gBw+H3cHH9K3FXink7dxarSIuh0W9jEgyxBdyK+pE3lErkONqVPNApwx8/SDekpxhZcbvcaN5BdDBmFYzDEqoR46YDEZuB6kh71MlT2ehfpnZZT8d2QGY0pQ+UI+41lnfUzzLRyejaxVXg0bMreA/afzWr7qHlDAFK7+nsDE2qUlAk2mlT9VTkz65mtU6ROivCvNxOBxTKqRoGpdsOUlJfHcsekd+nz0L+RA3BqZua63gs/s4JvOu7F6+GOq/Upsuy4Dlu74MidgIsx05tVNu7x5rA6ur6Z8qjDnhHOpufTCI2VYlIM3ZFIA4odaH2B16oi/1sjGHqLLvJICNlc/kXnFwf7kv9JlljR34VtnpJFI44QCfQ2OVhhRejUYHV8ll+pJC3jeO24lJaedF7GSPQ99ZlsqDJ7E0vXF0taj/w3FzhsVYR7qEoXoYRKejTO3aZU5Gj32NdqbJxkl1MzmDlW0uVz4b35en1YWS+Nqxr0DWmVWtMCGgLq2rWSCA3OgF8kxDhZbAXVIw9KAsG8p4EPYCXKUn
  template:
    metadata:
      creationTimestamp: null
      name: act-runner
      namespace: gitea
