---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: act-runner
  namespace: gitea
spec:
  encryptedData:
    GITEA_RUNNER_REGISTRATION_TOKEN: AgCu45Q3Gd2J5XB35PGRdGb8Ifa1kHgQnhYM8DR2Y/ar58wx9NIPDRgEegBqKNe3496W1nf7dis4mbTfBsDm7ROmpjpQyUzzZnXBWbCkG72Muu0wi16TmrKbTVMiGfzxcrRKEXB7CCgR0w2p0sGW6NzQ4qpUmXnYjb9O21QFLwsB2YyderizJTDnnrH9WUwLtY0bcoT6y9WUBeQkUEeDR5hTG/jStSpO6Kf8DqqkGNmWAKYNvzsZUBdjGc3wahKU+EYW3oUnbiDBziJ7UgggFo7foYoP2OzRZrSjryObvbpzSZywG9oOcXWw01DuH4bOe2Qcjsr0BYxvHmTHhmW23uLy+5cRq3zPJ+oaVOOG34l264U0eOSIaNqfOjkSVEvigBP+x+NglMB7K4xMwnQ7OYVx2NzC3yl5cyIKwAPbJXxXrY4etYDnh7t32NFn3woWlKYVhb99Q0stGsOkeFdRx1tHaoFXhsVRos7rETqvXFkytLSKiqeMwA0XYVwYr3BPJyhJomIMpPxa5gCxM8DbWBLW7/C8EPHLUu11KD4h0281gxLiobILLjrLHqm0Vh+psrLVtAPc3rHYzERHBJchQ+cracBkgnwdpx0NvxAw7047rJdtQaD+HohQgZRHZtXWnIEsLb7CvY3Kb3FXM/iDC37wPXF5e5EdrC/S01ibEjePIWTutbxJWN0r92BO1w+Lh7GPMh9tbsFbN8N0sCdvcCH5GKAFTSUBTOO0Cg2ZBNLjWq56lniTQaYa
  template:
    metadata:
      creationTimestamp: null
      name: act-runner
      namespace: gitea
