---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: act-runner
  namespace: gitea
spec:
  encryptedData:
    GITEA_RUNNER_REGISTRATION_TOKEN: AgDIiTWzkoTEWAVVbsNKCiERYVwXc6qoR8/3VqaYqPwY+K18RZE6I96lrkymmuNEqfWUkYPI2hcsKkwAz27jsMi9jvan+duJKWqxl2gUqZmPzXqpauLSTHi/7guZUfkadIqujJ83Jr16IsDNPnLl++hnFmtKCEqI3vL0plmLaxGMZ4FNPv2nRRFzR0UCtiGnUHVfMCVi2VbzZICN+FOnLtwERZpJe8+xiZCcCGJx1D5L/4xC+vOiKA1GgZMn3dpcl7+/LspZWzvJn+z82ZVSP/sThqUmzd3Qv+EQgJ19BrAYmrgD1SJzgk1pxkfvh9AfccrnQse10Pat0aNutBm4hx0zeeIvfJUQTJ+mlQcKwZ/sHbAtKwnJ9RXWJLy+pb9OJqx05tBBh/eGPxcQZGwO3iMABYFwJCFhtlAfQSQ5ZbK58Sp7T6TMj0+glhMRp2dPAlvK7xMhC1oJxp7Pi4AjXzuz/RMrsPeALTL184hESyR1DwHjd7Lsq/Ex1VuuuMcT6kCgy0KhH2+TJbBJoVp3KzGazzqEIl5LiQ/2iQQMntDT9xu8X+RZHUWPNICCneLqZLoGhj1qA7pou0YSdNcw6C5qJ8ZBFVk4UeCagXJFfYLcCIbbRXFLKe0znMcMSSAsn0On0hu7Ja8H3SOQHedcLAXC+tRKIVzZpM411xyeVLTwCLCAs59zSFPlMpxwl6uleEwy8ckuxIkS/4Akkeu0n/o7TzYdkOrD2TmwGoLJcGC9pc/Z0m/JMr6v
  template:
    metadata:
      creationTimestamp: null
      name: act-runner
      namespace: gitea
