---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: act-runner
  namespace: gitea
spec:
  encryptedData:
    GITEA_RUNNER_REGISTRATION_TOKEN: AgATcFZkZeHY9kYXGBQMk6viWffvvUJP+D51Mp4qHBv8c0T2yCFT6GLi8JE3OuEaBuxqVPd4D6qwH0K6ZTY2cfY/fIXim5ySZ+wePXZ467UWfoN/Ljms9+lvCJj/bNaQ6MAr4knk/lcCWMXe/J1rjULXRgn195HRzuNcM/teuEVUARXbj4MoTG18qaYExR6JNO0K+nXy5j0+79TzBkbsX3BfB/x5L2vtxDYJLpa7oswUDmsymlgOH1yZy+R8AaXRbX1qW6QsJg+KJAFtPdI3gggXq0JgOQaj/S5TaZK7up/A5Y4pJ9uPLU9KdpHNCnanx07btwHwef7A0HCLLiNEhT9ak5i5nFBqFYR2egJKhPmzuJmdxW0qf7aFqIZbSspoPkjpLm4gSVtpI15xCHNCl898++Iqn4caIpQSzt4LH+sBFIy6Bw+5DUPZ8j0jY00do99jo3jAHYWAIVPRyXirQcvUdl79MvV4TN2ZB8GOzYXQi/A6pCw0IbI59sQUjIUzUdKhiKhok2prXvq9+bLjO8FUpexuiKOvoly1E80VTMf1BxmMUtKTr+v7VK1bmUXwu4xlNhQ9nqoinbUKov1gJf+Ky/bIDn3CmdaNMLyiPbhw9/ZtS7CCVc6x2Z04fv/y9cbEcLWEgVRbAnHySrG6LPOoZmjwY7sd8y09koTnjctRVkX9qk/nX+bMRzPn2yi5SO4mBECU8kso3uebb2Xdn4EBoiyfbSbfORpXRArMMry61jVcrJrokGpB
  template:
    metadata:
      creationTimestamp: null
      name: act-runner
      namespace: gitea
