---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: act-runner
  namespace: gitea
spec:
  encryptedData:
    GITEA_RUNNER_REGISTRATION_TOKEN: AgAomJZ1fC2C0SyALo0u+2gj4DuhAwjQVK+wdCs7/WdZ2UsHJyDvCRvEeGLoQgFJgX/QTvx1lRn1iFYZXX5a/P2uOHGPBnBXhV633jSkwz1rmngt2ZkgtkCnm00JAogxciFQ9jJtm7IILsQPya7Yz/bqSYj7u5E28ev2rYC4PzglwxI1ajIXC1Gs+onKKKaOWw/aoG67aEsToxCmuCnSCBqPgd82rhAF9NIhxK5/J6gCjwZzvsprFfFoT5BDAlkQea6T8pojgmaDvA2Q7L724BXRaDBQZvbRW7cHFs+z+J56kIdbzEqUBijkdIJNZfSuivfbObHd7a/lseZP708WP4OtrGV6yvgeLf2BgkQLM0BHABwsBkDf8t3PuwCkUdVJ58A83iB2tuBP/Geugh0c2IftV8xFjfOLLQBugi532CIwfNadxI6SARXnUfaxdoNZ/F7/oZvDgUHpnegCMHO7fq+FxHCiJID4xeoCYB71URbsheo8nzuvEoVQBprs7UWe13qmcH1YykWWll+MeWJDdFq0Ke9GJM8B+vSDkFx+ZAyuh2H4VLAAM0Lzgzb96Htb/B9IR70jNxg232GuBeob3LVo7NPivJwT8BzJx+2RbnxoDy5o3C1Eq6Xx1etV30F+L5+QeegNPdCmA6wouf4fPao8AimBUx5DqWHDX2a2PTTcbslqtHh+kO2TlkCMymSD6XEIOUC00xg7Eu1pX++7UEf8jzgN9E1VbLnWptETPY8x+SJsCj1Dp0ga
  template:
    metadata:
      creationTimestamp: null
      name: act-runner
      namespace: gitea
