---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: act-runner
  namespace: gitea
spec:
  encryptedData:
    GITEA_RUNNER_REGISTRATION_TOKEN: AgBkIy3KZad0+TJQHgUGG0S275EKGaRG9FkrYBeumQ5SB8h6ePALyTNvO1TOo+8qK1B4UjwjpTYunHPLa/nC1aeQrpRHy6gI7W3DmiOn96TGpad+8UvY/9RI6g7tb7kyOR7vyBWks8JuhUaykHHsq3z351Zi5NrSYHX02YwQDT1Q4nhR9xU7kOfVkgCXs3+HHcy2LJ63KQaluD0imUGEwcAH2L0Dl7ylVt4FhxfYMKU4dsnUT6cETGBDZJrYyNLjJJU/266pzYGFaxfCs5nF/x+Djy/ifKCW9PfeneKztaFX/OqFXkT8dMovmPfmKmNgOYsSGZhkfyNe6DTuH+p8HsCSKqilF2I/9/+TXbpaiefQ6UKOif55UKmMoOEBTKOQmbsrpAkEKc4vVH9b2eZdQrjfKNaVV6696Y1TXQGWm7i8K0m3mZMZYjb0OM5Iu2ubNlcYIR0kRcKuuyaso/ZGQyjNE3/FUTvT0XjbPEpCeiYWbkDy/erlDUYJ2VTsH0t7qzvgh4veZz6hui2nbKzb1NOQ304Ztf8N51nEbwKoVMiH5JeR6OZ430NnLDLGGMFrf5WLVHzZju0FsuLS8Uehv5M0X69cKTLacsyNbbzKzAjpSCTSvnN7D9Z0RuUVbB5pclcTU1ThG0367NTtvCCWN0oplHrtWaossmLdK2wTvS+ESRYkyjhcuYsZjtRpaCAEc2CukoUTW+rRp9PLp3UxfFBr4ouKuQE9CbszyeLLQl4gkEIbdmbp68Ss
  template:
    metadata:
      creationTimestamp: null
      name: act-runner
      namespace: gitea
