apiVersion: batch/v1
kind: Job
metadata:
  name: create-additional-dbs
  namespace: postgres
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: create-additional-dbs
          image: postgres:16.6-alpine3.21
          env:
            - name: PGHOST
              value: "postgres-master"
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secrets
                  key: POSTGRES_PASSWORD
          envFrom:
            - configMapRef: { name: postgres-configs }
            - secretRef:    { name: postgres-secrets }
          command: ["/bin/sh", "-c"]
          args:
            - |
              # Attempt to change password for the user; if user does not exist then create the user.
              psql -v ON_ERROR_STOP=0 --username "$POSTGRES_USER" -c "ALTER USER $GITEA_USER WITH PASSWORD '$GITEA_PASSWORD'"
              psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" -c "CREATE USER $GITEA_USER WITH PASSWORD '$GITEA_PASSWORD'"
              
              # Attempt to create database if it does not exist.
              psql -v ON_ERROR_STOP=0 --username "$POSTGRES_USER" -c "CREATE DATABASE $GITEA_DB"
              psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" -c "ALTER DATABASE $GITEA_DB OWNER TO $GITEA_USER"
