apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: master
  labels: { app: postgres, role: master }
spec:
  selector: 
    matchLabels: { app: postgres, role: master }
  accessModes: 
    - ReadWriteOnce
