apiVersion: apps/v1
kind: StatefulSet
metadata: 
  name: master
spec:
  replicas: 1
  selector: 
    matchLabels: { app: postgres, role: master }
  template:
    metadata: 
      labels: { app: postgres, role: master }
    spec:
      nodeSelector: { node: main }
      volumes:
        - { name: data, persistentVolumeClaim: { claimName: master } }
      containers:
        - name: postgres
          image: postgres:16.6-alpine3.21
          ports:
            - { name: postgres, containerPort: 5432 }
          volumeMounts:
            - { name: data  , mountPath: /var/lib/postgresql/data }
          envFrom:
            - configMapRef: { name: master }
            - secretRef:    { name: main }
          livenessProbe:
            exec: { command: ["pg_isready", "-U", "postgres"] }
            initialDelaySeconds: 30 
            periodSeconds: 60
          readinessProbe:
            exec: { command: ["pg_isready", "-U", "postgres"] }
            initialDelaySeconds: 30 
            periodSeconds: 30
