namespace: postgres 
resources:
  - ../base
  - master/configs.yml
  - sealed-secrets.yml
  - master/pvc.yml

patches:
  - target:
      kind: StatefulSet 
      name: postgres-master
    path: master/stateful-set-patch.yml

# configMapGenerator:
# - name: postgres-config
#   files:
#   - configs/postgresql.conf
#   - configs/pg_hba.conf
