apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: postgres 
resources:
  - ../base
  - sealed-secrets.yml
  - jobs/create-gitea-db.yml
  - jobs/create-infobiz-db.yml

patches:
  - path: master/patch-pvc.yml
  - path: master/patch-service.yml

configMapGenerator:
  - name: master 
    # anyway secrets are hadled by sealed-secrets and we have to restart pods to apply new config
    # so in this case it is not make sense to use suffix hash for configmap
    # keep it simple
    options:
      disableNameSuffixHash: true
    literals:
      - POSTGRES_DB=main 
      - POSTGRES_USER=postgres 
