---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: postgres-secrets
  namespace: postgres
spec:
  encryptedData:
    GITEA_PASSWORD: AgAs7AXuIO0vpltXueCg5ArgK3nEebfZDjHCyhNQOte0+8zqTFUKZQd6/Ic6VC3PhkQZp6bR92v8B1jIGkZUSMH/m/191ray662oMFzQLoYfNVIhZf1cSHc/E6sFozA8Zef1nMUt4merbAVHvlTlsrkUO+FUc0T6Wq3YRI0HZZPKD0J5KRnUvH8tlM6I75qYrAV7biTLGC1N5xCyx9W3KQf7m0pF41X3aMIPQP8LbDdtITCRxU85H0Bqc6My1mPD7dHEjvDZ1Z9+SbaUiGGzJO+vVqv2MnZHI/JuN7VhnXmLuXUqF/gza8ndT8sWQyVM8FfZDQw66ofMNSKqTUqOFVMFBTWtoBgAZyms5GSnwMbvuQkwQjM2E33FwLPSDOydvWjQNB/2xMGzHrqHZ6AkP45p2i1FoXPA6KhpbT0OYmOhGP2SjC6wsP0BHFhk70Rq422epoUL6MZ5wr58sboe9SYrJHJ9RoXJsZK2UoI2Ms05euE3oXSszaThLLWaMUDvs1hAJiMxhl3Tm1EJDyijieGCUUHK/sbP5m1P2JFd7DWePqhvFzl2YXP7mfPqN+gauYEgfKvRcPakKzoxd8Imt7EX/XTF6FCOuHFQC6fhbIjIjsBKxv2lArgPzaolyl7+FE/1njCRfUjnUTtAoFudw6DPNirOCwL8sc2fuR+ssQZt3abMp8e3h0Jy9ZKomruNM3mHpGyPU3A=
    POSTGRES_PASSWORD: AgAq9Ih9Y07dM9nUR2NzUTl94C0w6+1BH7gpMQW7IxaBbHxg0UOboGiZL1cYKrOeJsxiOqrEq4CNPfp9xhVCKjeFu6xxXq9jR6BXp4DmJVTVNZGq2WG1U8yRxbndRCyX5Dd+GhQLALKBXmWZlKnv+IPy6f4dQSs4mkmWTI/5IDAudPjMzkgQOb70u7xEUVnLsofw+qPUOobE6ScO9gMUO8AX4xeLxIYM/T/0TKXpMkFvmnGf53GOyyiui5lJDg+oUkAFyaWNi5wHDErdb++5vjhffG0FD1TS/Oy3ascLrXx5ZnzpEPGs+8kBgrHws7tEV/nALaJjvIpKjymYErKjT1Z9MLLm1GkoR6AlssRXizI+9T5bPXiT3826xMm9OhXeec7FPh2sGu6a9hEtfdjtkn3ZweTwwDCHWEL1gCgn4xC6r0rHcwtdsNj5Ak6EJwBHpqL8FroEtVKafIG/hHEjkL8WJKHslAkygFIeAfnB7SS+E000MceUArKCq9kAg0ZatYrQ9PkpK8rH7qbkoihBnT/9bg/rqbik9cuPExygTgMw7/TfyzM06/9O63VTwXSTbNNA5wKVEBrIQDjRPG3VpbJ9LGL4EcmFjanQwmSOKlH4BTXLnIh0xpJ4M9F+pr7yTeEJZnU3eseGxUa8Qo0X8G53V2EmBJ4FQfv1dGAlN8UFjEei9vr3AnL4ZgxztdDq933txepDlBU=
  template:
    metadata:
      creationTimestamp: null
      name: postgres-secrets
      namespace: postgres
    type: Opaque
