---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: main
  namespace: postgres
spec:
  encryptedData:
    GITEA_PASSWORD: AgDMY4+QB+4saNSdobTLIkl1rrEbK2rE2rDmteU6sURLqxd+JKZS4isBU4CIWxHDuEXrY78B8p7kfAYE/ZvqrTy8x67dhGzEKHgj+477KhvJ3ZxckXu/RZW/JTTN6Tt7wI0SkG/1RYeKOT5kHOJvK4JK887ndYWnC3H6XUN2XkLxKfAK+zzLmpHdFQyr1aold9l4XOCA+oS4wFoFPKjyttjCnOZDVe5Lm3hJJRkTS/F6VG+L5PcNs3MMehk5sYZZxJRoTeRVhn/bXxUyrYTysRTErHRzvrM473El2yFfa1qGym+khTK88DTOrnl1W4fKrMlGlsCrswOFkSqDCPaKiq0PRS7CA+b9agkg+MJ1IOOnHZuJMh218XXlRnSo8MuL6P6MMPr9JEbdzeAU25iXwhUOLNjFat6XDHW/++CY4ebE636Ip3a+7PudYCwsB3RGHcQd53gLsiSqlBnA0WfGJcqG8Bw+McDb4N9r14BNT/ieff9psDvMGeksxNEQ0g5nH4mss7dz6WhogwhNBNCK/SI5KQfnK9/URyTYqrrGPe2/CvBQ+TEOEJw4qQIUw0Vo5NbOJBJ6Ky6L8cwI0lLCbjNDheexyCqYvPQfaZjGCLTorNGR+D0liyXoSFn+ixjh7O4pzT5DmtUsQYSfFHJWaqiZk/bsN4S3i5vasAB3snN+xPsJ9LVYi8VecHPIlADdma5j9K1T/TQ=
    POSTGRES_PASSWORD: AgARwSUU+w+HP5Xkjxf5xENttNvNnzwa8UpKPQB/V9c5m0Qem4t4vWi+NpkrQEmtyJ3RASsBndsVzjDYaBYhbTJ+YLl0fpV8KiMFeSL5uYoWdjdOU75oOKYvSJ3r3GQlsLrR8lh7sxbQSirtJjqS1gkOcLVRL0YQtpOyfgFyuZFGiBmAPM2M56tfjgo9g7w5QBQxDXoIaEVgPvLJsY7z/K/c+qKRjkA57kJ+t9xI1gzjPc/XyXnuhqneX3Ph/bZdMjWLdZNUgfu/eEoLEWib/ZrVy13kIfXxTGaw0sqy4LOGWiDYeyNCEjA+5Husq2k4PGvSpaogQ8SGujnOO6xFqDYz0GPdjpizdi9IpOsWS92GuUkN30Uy3OCIExVb25u94/2dmJvBUsNaXa44+GdH2jxjwyXSkwvOs/Q9cddn65I75mVds1WBILSoVWR+fLeSsiquj0z0GKsUuH50zeO/syJxFnOCLW0WSvGjzAtnh6OuFTD/maWuXUiOaVD1EQKM8g3CL5qpJ6NsOXnQONPoA3vRO6F35hJYQwjD1RcjRbU2byPynmDdvUeiKe6lJVv+Ow0ymtKugW7pVT4Qcj93iQgvAZSihHHz159z/fTuXNAOmq26xv4vKPycR5/98x+At2i2M/KIG7khn1IMw5Kg2iXg158kUUn8Vs//hsIgp3PMDztUBtG5r5a/pwVlLygqGbasNs1kU10=
  template:
    metadata:
      creationTimestamp: null
      name: main
      namespace: postgres
