apiVersion: v1
kind: Secret
metadata:
  name: postgres-secrets
  # you have to declare namespace here for Sealed Secrets to work in proper namespace
  namespace: postgres
type: Opaque
data:
  # echo -n "secret" | base64
  POSTGRES_PASSWORD: MTIzNDU2  # 123456