apiVersion: v1
kind: Secret
metadata:
  name: main
  # you have to declare namespace here for Sealed Secrets to work in proper namespace
  namespace: postgres
data:
  # echo -n "secret" | base64
  POSTGRES_PASSWORD: MTIzNDU2  # 123456
  # passwords for other users, it used in jobs
  GITEA_PASSWORD    : MTIzNDU2  # 123456
  INFOBIZ_PASSWORD  : MTIzNDU2  # 123456
