apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: propagandon-dev 
resources:
  - namespace.yml
  - ../base
  - service.yml
  - ingress.yml

images:
  - { name: front-react, newTag: dev, newName: gitea.propagandon.online/propagandon/propagandon-front-react }
  - { name: back       , newTag: dev, newName: gitea.propagandon.online/propagandon/propagandon-back }

secretGenerator:
- { name: back-secret   , envs: [ .env.back.secret ] }
- { name: pub-sub-secret, envs: [ .env.pub-sub.secret ] }


configMapGenerator:
  - name: pub-sub-config 
    literals:
      - CENTRIFUGO_LOG_LEVEL=debug
      - CENTRIFUGO_ALLOWED_ORIGINS="['*']"
  - name: back-config 
    literals:
      - DEBUG=True
      - ALLOWED_HOSTS=dev.propagandon.online
      - CSRF_TRUSTED_ORIGINS=https://dev.propagandon.online
      - ADMINS=
      - MANAGERS=
      - CELERY_BROKER_URL=redis://:@redis:6379/0
      - DB_HOST=postgres
      - DB_NAME=propagandon-dev
      - DB_USER=postgres
      - S3_ENDPOINT_URL=http://minio:9000
      - S3_BUCKET_NAME=propagandon-dev

patchesStrategicMerge:
  - deployment.back.yml
  - deployment.beat.yml
  - deployment.flower.yml
  - deployment.front.yml
  - deployment.worker.yml
