apiVersion: apps/v1
kind: Deployment 
metadata: 
  name: flower
  labels: { app: infobiz }
spec:
  replicas: 1 
  selector: 
    matchLabels: { app: infobiz, component: flower }
  template:
    metadata: 
      labels: { app: infobiz, component: flower }
    spec:
      nodeSelector: { node: main }
      containers:
        - name: back-flower
          image: back 
          imagePullPolicy: Always
          command: [ "celery", "-A", "main", "flower", "--port=8888", "url_prefix=flower" ]
          ports:
            - { name: flower-http, containerPort: 8888 }
          envFrom:
            - configMapRef: { name: back }
            - secretRef:    { name: back }
          resources: {} 
