apiVersion: apps/v1
kind: Deployment 
metadata: 
  name: worker
  labels: { app: infobiz }
spec:
  replicas: 1 
  selector: 
    matchLabels: { app: infobiz, component: worker }
  template:
    metadata: 
      labels: { app: infobiz, component: worker }
    spec:
      nodeSelector: { node: main }
      imagePullSecrets:
        - name: registry-credentials
      containers:
        - name: worker
          image: back 
          imagePullPolicy: Always
          command: [ "celery", "-A", "main", "worker", "-l", "info" ]
          envFrom:
            - configMapRef: { name: back }
            - secretRef:    { name: back }
          resources: {} 
