apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: frigate 
resources:
  - ../base 
  - sealed-secrets.yml

patches:
  - path: patch-pvc/data.yml
  - path: patch-pvc/dshm.yml
  - path: patch-pvc/media.yml
  - path: patch-pvc/tmp.yml
  - path: patch-service.yml

configMapGenerator:
  - name: main 
    # anyway secrets are hadled by sealed-secrets and we have to restart pods to apply new config
    # so in this case it is not make sense to use suffix hash for configmap
    # keep it simple
    options:
      disableNameSuffixHash: true
    files:
      - config.yml=config.yml