apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: postgres 
resources:
  - ../base
  - master/pvc.yml
  - master/pv.yml
  - configs.yml
  - sealed-secrets.yml
  - service.yml
