apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: postgres 
resources:
  - namespace.yml
  - ../base
  - master/pvc.yml
  - master/pv.yml
  - configs.yml
  - sealed-secrets.yml
  - service.yml

patches:
  - path: master/node-selector-patch.yml
    target:
      kind: StatefulSet 
      name: postgres-master