---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: main
  namespace: postgres
spec:
  encryptedData:
    GITEA_PASSWORD: AgCtD86+229UUyOvi55B15tPBwp8FxEyI5c43sgbSE5iSyR8syoxdtbQbQxSUs8RDhs3DqI2OawODCx6vQOWOWbMnNsj1bt8kcS5FKm/KZ8HRTlroS+rjFLjiez22S4qWQI1DwUw3MFNn5ubDt4/daCbBrlOgokuzZXVp9y3K/DX4dMd46gL1MZJXSAgsATvSXkft69EG4GBox41BXxner/yeh30zECtjNhI/2YovkSHXpZajxgicbcYYZv2XqD9hkrWGyjlfufdLAe0ClPpJWb10eHC3IGRKPvovETg39pOYtoN8QFD82VBBNj6UPh5+gp2LEthFIyQYx3zKGt1SSm7615PFse3Mt12JdYHQfAmk553D0h6bJ6Mp/7hJpC9X1ZP97JyQy08hM+dLTHLCm2dpzjKEWEGj0jrSDoVgY/9vhC+h3tYd7GFw/Jr912+TKt7PxChCC4bizFvHv5Nimi3EaZY1yB8Sn/IhAkxuo4l+v3WCHPfCnghdJXPeOzgwrwz/H92fObiKNlcVoYNfYJzQhv2L9LSNhaqyhV9tLHvab0LVMcq3QK17gRbwKLeJnTT42ujCJZjcHMMZsQXshuRtDhfbfr4kSFnh1netlJ7EgG3xsEVn4Y0CFmpQk9BAIjsgY82blYYPINC9kJAWLRx9PbVE30rLIf2x645+ghDOzPiHd1r0CE2KK3H3s+zLpVEabq/WYdPEGi4uJQ=
    POSTGRES_PASSWORD: AgB22WpoI78UZDr17Hqywc98riYgJwGFURmc+R7TmZTmGoyBC/IzlfRw9WmEf47u+/2w3+AzR69aDczWjckCDsGauOp4biCBur1htUs+Ulj/36EKhrii4iNgbLtt+rT8dNfVcZZ68G39L4jc3A03TgqiEdnoVeqG0mrtu+uAwZIrtmPAvcOwS62PlJSmvo5TBuou7ysxM8JoxRXelBs0Zx/rtQoSUZwvmwNNbrf4nnPSvR+rJC5Cyrorjd3BRyURkCHti6/jofiKbxeNewfdl0N1EuQuJx2ZPSrrgoQi/F0OwUGdfHPBpP1VGkYtmreRl288bqSzzYxX5B4j2k77+wc7i5m6HR9bcjT79nl7eCklBgz7eTlRMagXVzDmyRj2sWUzLeMrmvbNm+XDQShrapZ6Pm5zAvBzpEAtdXo2jcHp6kZYITU8iv2Unzku7wBsXpbQwDyfTEtwL079vkxhxf9UMJoAnHZpuP4HcJ1nSy1i6rmvVvXvrXpRgZyvGWrRsEGLcX5nZLUz1RIeAoHrwnX+rnKJjipaoUnnFw0FNrCdImvFPsIMdKwcn1EqgvW5JwiH8q/N09Thn6LUpOdjN5CIJKBKDYTJlXK4nePfXY4TJ+OQFgSUJfPhqy/y8oGeWyhRH968Fhr7m4EnXOokxAZSi4ocrlQpzivHycPZRjDOq75O8S45e30UgVsFaklOQU0LlortWiIPum/+VbU=
  template:
    metadata:
      creationTimestamp: null
      name: main
      namespace: postgres
