apiVersion: v1
kind: Service
metadata:
  name: postgres-master-outside
spec:
  selector: { app: postgres, role: master }
  type: NodePort
  ports:
    - { name: postgres, port: 5432, targetPort: postgres }
  externalIPs:
    - 10.8.1.11 
