apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitea-act-runner
spec:
  replicas: 1
  selector:
    matchLabels: { app: gitea-act-runner }
  strategy: {}
  template:
    metadata:
      labels: { app: gitea-act-runner }
    spec:
      restartPolicy: Always
      volumes:
        - { name: runner-data, persistentVolumeClaim: { claimName: gitea-act-runner } }
      initContainers:
        - name: fix-data-permissions
          image: busybox
          command: ["sh", "-c", "chown -R 1000:1000 /data"]
          volumeMounts:
            - { name: runner-data, mountPath: /data }
      containers:
        - name: gitea-act-runner
          # image: vegardit/gitea-act-runner:dind-latest
          image: vegardit/gitea-act-runner:dind-rootless-latest
          envFrom:
            - configMapRef: { name: gitea-act-runner }
            - secretRef   : { name: gitea-act-runner }
          resources: {}
          volumeMounts:
            - { name: runner-data, mountPath: /data }
          securityContext:
            privileged: true
