apiVersion: apps/v1
kind: Deployment
metadata:
  name: act-runner
spec:
  replicas: 1
  selector:
    matchLabels: { app: gitea, component: act-runner }
  strategy: {}
  template:
    metadata:
      labels: { app: gitea, component: act-runner }
    spec:
      nodeSelector: { node: main }
      restartPolicy: Always
      volumes:
        - { name: data, persistentVolumeClaim: { claimName: act-runner } }
      initContainers:
        - name: fix-data-permissions
          image: busybox
          command: ["sh", "-c", "chown -R 1000:1000 /data"]
          volumeMounts:
            - { name: data, mountPath: /data }
      containers:
        - name: act-runner
          # image: vegardit/gitea-act-runner:dind-latest
          image: vegardit/gitea-act-runner:dind-rootless-latest
          envFrom:
            - configMapRef: { name: act-runner }
            - secretRef   : { name: act-runner }
          resources: {}
          volumeMounts:
            - { name: data, mountPath: /data }
          securityContext:
            privileged: true
