apiVersion: v1
kind: PersistentVolumeClaim
metadata: 
  name: act-runner
spec:
  selector: 
    matchLabels: { app: gitea, component: act-runner }
  accessModes: 
    - ReadWriteOnce
  resources: 
    requests: 
      storage: 20Gi
